config/routes.rb
Rails.application.routes.draw do
  root 'web_configs#index'
  resources :web_configs

end

app/models/web_config.rb
class WebConfig < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/web_configs_controller.rb
class WebConfigsController < ApplicationController
  before_action :set_web_config, only: [:show, :edit, :update, :destroy]

  # GET /web_configs
  # GET /web_configs.json
  def index
    @web_configs = WebConfig.all
  end

  # GET /web_configs/1
  # GET /web_configs/1.json
  def show
  end

  # GET /web_configs/new
  def new
    @web_config = WebConfig.new
  end

  # GET /web_configs/1/edit
  def edit
  end

  # POST /web_configs
  # POST /web_configs.json
  def create
    @web_config = WebConfig.new(web_config_params)

    respond_to do |format|
      if @web_config.save
        format.html { redirect_to @web_config, notice: 'Web config was successfully created.' }
        format.json { render :show, status: :created, location: @web_config }
      else
        format.html { render :new }
        format.json { render json: @web_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /web_configs/1
  # PATCH/PUT /web_configs/1.json
  def update
    respond_to do |format|
      if @web_config.update(web_config_params)
        format.html { redirect_to @web_config, notice: 'Web config was successfully updated.' }
        format.json { render :show, status: :ok, location: @web_config }
      else
        format.html { render :edit }
        format.json { render json: @web_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /web_configs/1
  # DELETE /web_configs/1.json
  def destroy
    @web_config.destroy
    respond_to do |format|
      format.html { redirect_to web_configs_url, notice: 'Web config was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_web_config
      @web_config = WebConfig.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def web_config_params
      params.require(:web_config).permit(:directory, :scan_interval, :old)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/web_configs_helper.rb
module WebConfigsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DiskQuotaWebConfig</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/web_configs/_form.html.erb
<%= form_for(@web_config) do |f| %>
  <% if @web_config.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@web_config.errors.count, "error") %> prohibited this web_config from being saved:</h2>

      <ul>
      <% @web_config.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :directory %><br>
    <%= f.text_area :directory %>
  </div>
  <div class="field">
    <%= f.label :scan_interval %><br>
    <%= f.text_field :scan_interval %>
  </div>
  <div class="field">
    <%= f.label :old %><br>
    <%= f.text_field :old %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/web_configs/edit.html.erb
<h1>Editing Web Config</h1>

<%= render 'form' %>

<%= link_to 'Show', @web_config %> |
<%= link_to 'Back', web_configs_path %>

app/views/web_configs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Web Configs</h1>

<table>
  <thead>
    <tr>
      <th>Directory</th>
      <th>Scan interval</th>
      <th>Old</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @web_configs.each do |web_config| %>
      <tr>
        <td><%= web_config.directory %></td>
        <td><%= web_config.scan_interval %></td>
        <td><%= web_config.old %></td>
        <td><%= link_to 'Show', web_config %></td>
        <td><%= link_to 'Edit', edit_web_config_path(web_config) %></td>
        <td><%= link_to 'Destroy', web_config, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Web config', new_web_config_path %>

app/views/web_configs/new.html.erb
<h1>New Web Config</h1>

<%= render 'form' %>

<%= link_to 'Back', web_configs_path %>

app/views/web_configs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Directory:</strong>
  <%= @web_config.directory %>
</p>

<p>
  <strong>Scan interval:</strong>
  <%= @web_config.scan_interval %>
</p>

<p>
  <strong>Old:</strong>
  <%= @web_config.old %>
</p>

<%= link_to 'Edit', edit_web_config_path(@web_config) %> |
<%= link_to 'Back', web_configs_path %>